### PR TITLE
Update build.rs

### PR DESCRIPTION
**Pull request by keorn**
fixes serde errors

### CODE REVIEW

**Comment by debris** [comment]
travis failing

**Comment by keorn** [comment]
Yep, I saw that. Trying to figure it out, but not sure about the serde workings. When I included ethabi as dependency without this commit it was failing to compile, but now it fails standalone. It comes from the zkSNARKs guys: https://github.com/gancherj/ethabi

**Comment by debris** [comment]
It's caused by locked dependencies in `Cargo.lock`. Unfortunately updating dependencies is not enough, cause some tests are failing with new version of serde. I will fix them and merge the pr

**Comment by keorn** [comment]
Ah I see, thanks.

**Comment by debris** [comment]
related issue: https://github.com/serde-rs/serde/issues/487

**Comment by debris** [comment]
@keorn please review #4

**Pull request closed without merging**
